version: '3'
services:
  bot:
    restart: unless-stopped
    image: telegram_ukranian
    container_name: telegram_ukranian_PROD
    networks: 
      - bots
      - backend
networks: 
  bots:
    external: true
  backend:
    external: true


